"""
Short Rate 3D Yield Surface Visualization
==========================================
Streamlit + Three.js application for interactive 3D visualization
of yield surfaces generated by short rate models.

Usage:
    streamlit run app.py
"""

import json
import numpy as np
import streamlit as st
from short_rate_models import VasicekModel, CIRModel, HullWhiteModel, HoLeeModel
from simulation import MonteCarloSimulator


# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Short Rate 3D Surface",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Sidebar: Model & Parameters ──────────────────────────────────────────────
st.sidebar.title("Short Rate Model")

model_name = st.sidebar.selectbox(
    "Model",
    ["Vasicek", "CIR", "Hull-White", "Ho-Lee"],
    index=0,
)

st.sidebar.markdown("---")
st.sidebar.subheader("Parameters")

r0 = st.sidebar.slider("r₀ (Initial Rate)", 0.001, 0.15, 0.03, 0.001, format="%.3f")
sigma = st.sidebar.slider("σ (Volatility)", 0.001, 0.10, 0.015, 0.001, format="%.3f")

has_kappa = model_name in ("Vasicek", "CIR", "Hull-White")
has_theta = model_name in ("Vasicek", "CIR")

if has_kappa:
    kappa = st.sidebar.slider("κ (Mean Reversion)", 0.01, 2.0, 0.3, 0.01, format="%.2f")
if has_theta:
    theta = st.sidebar.slider("θ (Long-run Mean)", 0.001, 0.15, 0.05, 0.001, format="%.3f")

st.sidebar.markdown("---")
st.sidebar.subheader("Simulation")

T_sim = st.sidebar.slider("Simulation Horizon (years)", 1.0, 10.0, 3.0, 0.5)
n_time_grid = st.sidebar.slider("Time Grid (t steps)", 10, 80, 40, 5)
n_maturity_grid = st.sidebar.slider("Maturity Grid (T steps)", 10, 80, 40, 5)
max_maturity = st.sidebar.slider("Max Maturity τ (years)", 1.0, 30.0, 10.0, 1.0)
n_paths = st.sidebar.slider("MC Paths (for simulation)", 200, 5000, 1000, 100)
n_display_paths = st.sidebar.slider("Display Paths (rate chart)", 5, 100, 30, 5)
seed = st.sidebar.number_input("Random Seed", value=42, step=1)

st.sidebar.markdown("---")
st.sidebar.subheader("Visual Style")
color_scheme = st.sidebar.selectbox(
    "Color Scheme",
    ["Antigravity Neon", "Thermal", "Ocean", "Monochrome"],
    index=0,
)
show_wireframe = st.sidebar.checkbox("Wireframe overlay", value=True)
show_particles = st.sidebar.checkbox("Particle effects", value=True)
auto_rotate = st.sidebar.checkbox("Auto-rotate", value=True)


# ── Build Model ──────────────────────────────────────────────────────────────
def initial_forward_rate(t):
    return r0 + 0.008 * (1 - np.exp(-t / 2))


if model_name == "Vasicek":
    model = VasicekModel(kappa=kappa, theta=theta, sigma=sigma, r0=r0)
elif model_name == "CIR":
    model = CIRModel(kappa=kappa, theta=theta, sigma=sigma, r0=r0)
elif model_name == "Hull-White":
    model = HullWhiteModel(kappa=kappa, sigma=sigma, r0=r0,
                           initial_curve=initial_forward_rate)
else:
    model = HoLeeModel(sigma=sigma, r0=r0, initial_curve=initial_forward_rate)


# ── Simulate ─────────────────────────────────────────────────────────────────
@st.cache_data(show_spinner="Simulating short rate paths...")
def run_simulation(_model_name, _r0, _sigma, _kappa_val, _theta_val, _T, _n_paths, _seed,
                   _n_time_grid, _n_maturity_grid, _max_maturity):
    """Run simulation and compute yield surface data."""

    # Rebuild model inside cached function
    def fwd(t):
        return _r0 + 0.008 * (1 - np.exp(-t / 2))

    if _model_name == "Vasicek":
        mdl = VasicekModel(kappa=_kappa_val, theta=_theta_val, sigma=_sigma, r0=_r0)
    elif _model_name == "CIR":
        mdl = CIRModel(kappa=_kappa_val, theta=_theta_val, sigma=_sigma, r0=_r0)
    elif _model_name == "Hull-White":
        mdl = HullWhiteModel(kappa=_kappa_val, sigma=_sigma, r0=_r0, initial_curve=fwd)
    else:
        mdl = HoLeeModel(sigma=_sigma, r0=_r0, initial_curve=fwd)

    # --- Step 1: Simulate short rate paths ---
    n_steps = int(_T * 252)
    sim = MonteCarloSimulator(mdl, seed=_seed)
    times, paths = sim.simulate(T=_T, n_steps=n_steps, n_paths=_n_paths)

    # Mean path for zero curve computation
    mean_path = paths.mean(axis=0)

    # --- Step 2: Compute yield surface Y(t, T) ---
    t_grid = np.linspace(0, _T * 0.9, _n_time_grid)
    tau_grid = np.linspace(0.1, _max_maturity, _n_maturity_grid)

    surface_t = []
    surface_tau = []
    surface_y = []

    for ti_idx, t_val in enumerate(t_grid):
        # Find closest time index in simulation
        sim_idx = int(t_val / _T * n_steps)
        sim_idx = min(sim_idx, n_steps - 1)
        r_t = mean_path[sim_idx]

        for tau_val in tau_grid:
            T_mat = t_val + tau_val
            # Compute zero-coupon bond price analytically
            if hasattr(mdl, 'bond_price_analytical'):
                price = mdl.bond_price_analytical(r_t, t_val, T_mat)
            else:
                # Fallback: use Vasicek-like formula with flat rate approximation
                price = np.exp(-r_t * tau_val)

            price = max(price, 1e-10)
            y = -np.log(price) / tau_val
            surface_t.append(float(t_val))
            surface_tau.append(float(tau_val))
            surface_y.append(float(y))

    # Paths for 2D chart (subsample)
    path_indices = np.linspace(0, _n_paths - 1, min(200, _n_paths), dtype=int)
    sampled_paths = paths[path_indices]

    # Subsample time for paths chart
    time_indices = np.linspace(0, n_steps, min(500, n_steps + 1), dtype=int)

    return {
        "times": times[time_indices].tolist(),
        "paths": (sampled_paths[:, time_indices] * 100).tolist(),  # in percent
        "mean_path": (mean_path[time_indices] * 100).tolist(),
        "surface_t": surface_t,
        "surface_tau": surface_tau,
        "surface_y": [v * 100 for v in surface_y],  # in percent
        "n_t": _n_time_grid,
        "n_tau": _n_maturity_grid,
        "stats": {
            "terminal_mean": float(paths[:, -1].mean() * 100),
            "terminal_std": float(paths[:, -1].std() * 100),
            "min_rate": float(paths.min() * 100),
            "max_rate": float(paths.max() * 100),
            "neg_pct": float((paths < 0).any(axis=1).mean() * 100),
        },
    }


kappa_val = kappa if has_kappa else 0.3
theta_val = theta if has_theta else r0

data = run_simulation(
    model_name, r0, sigma, kappa_val, theta_val,
    T_sim, n_paths, seed, n_time_grid, n_maturity_grid, max_maturity,
)

# ── Header ───────────────────────────────────────────────────────────────────
st.markdown(f"""
<h1 style="text-align:center; color: #e0e0e0; font-family: 'Courier New', monospace;">
    {model_name} — 3D Yield Surface
</h1>
""", unsafe_allow_html=True)

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Terminal Mean", f"{data['stats']['terminal_mean']:.3f}%")
col2.metric("Terminal Std", f"{data['stats']['terminal_std']:.3f}%")
col3.metric("Min Rate", f"{data['stats']['min_rate']:.3f}%")
col4.metric("Max Rate", f"{data['stats']['max_rate']:.3f}%")
col5.metric("Neg Rate Paths", f"{data['stats']['neg_pct']:.1f}%")


# ── Three.js 3D Visualization ────────────────────────────────────────────────
def build_threejs_html(data: dict, config: dict) -> str:
    """Build the full HTML+JS for the Three.js 3D yield surface."""

    color_schemes = {
        "Antigravity Neon": {
            "bg": "0x0a0a1a",
            "low": "0x00ffff",
            "mid": "0xff00ff",
            "high": "0xffff00",
            "wire": "0x00ff88",
            "particle": "0x00ffff",
            "ambient": "0x222244",
            "grid": "0x1a1a3a",
        },
        "Thermal": {
            "bg": "0x0a0a0a",
            "low": "0x0000ff",
            "mid": "0xff4400",
            "high": "0xffff00",
            "wire": "0xff6600",
            "particle": "0xff4400",
            "ambient": "0x331100",
            "grid": "0x1a1000",
        },
        "Ocean": {
            "bg": "0x001020",
            "low": "0x004466",
            "mid": "0x0088aa",
            "high": "0x00ffcc",
            "wire": "0x006688",
            "particle": "0x00ccff",
            "ambient": "0x002233",
            "grid": "0x001a2a",
        },
        "Monochrome": {
            "bg": "0x0a0a0a",
            "low": "0x333333",
            "mid": "0x888888",
            "high": "0xffffff",
            "wire": "0x555555",
            "particle": "0xaaaaaa",
            "ambient": "0x222222",
            "grid": "0x1a1a1a",
        },
    }

    cs = color_schemes[config["color_scheme"]]
    data_json = json.dumps(data)

    return f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * {{ margin:0; padding:0; }}
  body {{ overflow:hidden; background:#0a0a1a; }}
  canvas {{ display:block; }}
  #info {{
    position:absolute; top:12px; left:16px; color:#8888aa;
    font:12px 'Courier New', monospace; pointer-events:none;
    text-shadow: 0 0 8px rgba(0,255,255,0.3);
  }}
  #tooltip {{
    position:absolute; display:none; padding:8px 14px;
    background:rgba(10,10,30,0.92); border:1px solid rgba(0,255,255,0.3);
    color:#e0e0e0; font:12px 'Courier New', monospace;
    border-radius:4px; pointer-events:none;
    box-shadow: 0 0 20px rgba(0,255,255,0.15);
  }}
</style>
</head>
<body>
<div id="info">
  Drag to rotate &middot; Scroll to zoom &middot; Hover for values
</div>
<div id="tooltip"></div>

<script type="importmap">
{{
  "imports": {{
    "three": "https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.js",
    "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.164.1/examples/jsm/"
  }}
}}
</script>

<script type="module">
import * as THREE from 'three';
import {{ OrbitControls }} from 'three/addons/controls/OrbitControls.js';

// ── DATA ──
const DATA = {data_json};
const nT = DATA.n_t;
const nTau = DATA.n_tau;

// ── SCENE SETUP ──
const scene = new THREE.Scene();
scene.background = new THREE.Color({cs['bg']});
scene.fog = new THREE.FogExp2({cs['bg']}, 0.012);

const camera = new THREE.PerspectiveCamera(55, window.innerWidth / window.innerHeight, 0.1, 500);
camera.position.set(28, 22, 32);

const renderer = new THREE.WebGLRenderer({{ antialias: true, alpha: true }});
renderer.setSize(window.innerWidth, window.innerHeight);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.2;
document.body.appendChild(renderer.domElement);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.05;
controls.autoRotate = {'true' if config['auto_rotate'] else 'false'};
controls.autoRotateSpeed = 0.5;
controls.target.set(0, 5, 0);

// ── LIGHTS ──
scene.add(new THREE.AmbientLight({cs['ambient']}, 0.6));
const dirLight = new THREE.DirectionalLight(0xffffff, 0.8);
dirLight.position.set(20, 30, 20);
scene.add(dirLight);
const pointLight1 = new THREE.PointLight({cs['low']}, 1.5, 80);
pointLight1.position.set(-15, 20, -15);
scene.add(pointLight1);
const pointLight2 = new THREE.PointLight({cs['high']}, 1.2, 80);
pointLight2.position.set(15, 15, 15);
scene.add(pointLight2);

// ── GRID ──
const gridHelper = new THREE.GridHelper(60, 30, {cs['grid']}, {cs['grid']});
gridHelper.position.y = -0.5;
scene.add(gridHelper);

// ── BUILD YIELD SURFACE ──
const surfaceT = DATA.surface_t;
const surfaceTau = DATA.surface_tau;
const surfaceY = DATA.surface_y;

// Normalize to scene coordinates
const tMin = Math.min(...surfaceT), tMax = Math.max(...surfaceT);
const tauMin = Math.min(...surfaceTau), tauMax = Math.max(...surfaceTau);
const yMin = Math.min(...surfaceY), yMax = Math.max(...surfaceY);
const yRange = yMax - yMin || 1;

const scaleX = 30;  // t axis
const scaleZ = 30;  // tau axis
const scaleY = 18;  // yield axis

function toSceneCoords(t, tau, y) {{
  const x = ((t - tMin) / (tMax - tMin || 1) - 0.5) * scaleX;
  const z = ((tau - tauMin) / (tauMax - tauMin || 1) - 0.5) * scaleZ;
  const yNorm = (y - yMin) / yRange;
  const yScene = yNorm * scaleY;
  return [x, yScene, z];
}}

// BufferGeometry for surface mesh
const geometry = new THREE.BufferGeometry();
const vertices = [];
const colors = [];
const indices = [];
const uvs = [];

const colorLow = new THREE.Color({cs['low']});
const colorMid = new THREE.Color({cs['mid']});
const colorHigh = new THREE.Color({cs['high']});

for (let i = 0; i < nT * nTau; i++) {{
  const [x, y, z] = toSceneCoords(surfaceT[i], surfaceTau[i], surfaceY[i]);
  vertices.push(x, y, z);

  const norm = (surfaceY[i] - yMin) / yRange;
  const color = new THREE.Color();
  if (norm < 0.5) {{
    color.lerpColors(colorLow, colorMid, norm * 2);
  }} else {{
    color.lerpColors(colorMid, colorHigh, (norm - 0.5) * 2);
  }}
  colors.push(color.r, color.g, color.b);

  const u = (i % nTau) / (nTau - 1);
  const v = Math.floor(i / nTau) / (nT - 1);
  uvs.push(u, v);
}}

// Build triangle indices
for (let i = 0; i < nT - 1; i++) {{
  for (let j = 0; j < nTau - 1; j++) {{
    const a = i * nTau + j;
    const b = a + 1;
    const c = a + nTau;
    const d = c + 1;
    indices.push(a, c, b);
    indices.push(b, c, d);
  }}
}}

geometry.setAttribute('position', new THREE.Float32BufferAttribute(vertices, 3));
geometry.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
geometry.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2));
geometry.setIndex(indices);
geometry.computeVertexNormals();

// Surface material — glass-like with vertex colors
const surfaceMat = new THREE.MeshPhongMaterial({{
  vertexColors: true,
  transparent: true,
  opacity: 0.78,
  side: THREE.DoubleSide,
  shininess: 90,
  specular: new THREE.Color(0x333355),
}});
const surfaceMesh = new THREE.Mesh(geometry, surfaceMat);
scene.add(surfaceMesh);

// Wireframe overlay
{'const wireMat = new THREE.MeshBasicMaterial({ color: ' + cs['wire'] + ', wireframe: true, transparent: true, opacity: 0.15 });' if config['show_wireframe'] else ''}
{'const wireMesh = new THREE.Mesh(geometry.clone(), wireMat); scene.add(wireMesh);' if config['show_wireframe'] else ''}

// ── GLOW EDGES ──
const edgeGeo = new THREE.EdgesGeometry(geometry, 15);
const edgeMat = new THREE.LineBasicMaterial({{ color: {cs['wire']}, transparent: true, opacity: 0.25 }});
const edgeMesh = new THREE.LineSegments(edgeGeo, edgeMat);
scene.add(edgeMesh);

// ── FLOATING PARTICLES ──
{'const particleCount = ' + str(800 if show_particles else 0) + ';'}
const particleGeom = new THREE.BufferGeometry();
const pPositions = new Float32Array(particleCount * 3);
const pVelocities = new Float32Array(particleCount * 3);
for (let i = 0; i < particleCount; i++) {{
  pPositions[i * 3] = (Math.random() - 0.5) * 50;
  pPositions[i * 3 + 1] = Math.random() * 25;
  pPositions[i * 3 + 2] = (Math.random() - 0.5) * 50;
  pVelocities[i * 3] = (Math.random() - 0.5) * 0.01;
  pVelocities[i * 3 + 1] = (Math.random() - 0.5) * 0.02;
  pVelocities[i * 3 + 2] = (Math.random() - 0.5) * 0.01;
}}
particleGeom.setAttribute('position', new THREE.Float32BufferAttribute(pPositions, 3));
const particleMat = new THREE.PointsMaterial({{
  color: {cs['particle']},
  size: 0.15,
  transparent: true,
  opacity: 0.5,
  blending: THREE.AdditiveBlending,
  depthWrite: false,
}});
const particles = new THREE.Points(particleGeom, particleMat);
scene.add(particles);

// ── AXIS LABELS (sprites) ──
function makeLabel(text, position, color = 0xaaaacc) {{
  const canvas = document.createElement('canvas');
  canvas.width = 256; canvas.height = 64;
  const ctx = canvas.getContext('2d');
  ctx.font = 'bold 28px Courier New';
  ctx.fillStyle = '#' + new THREE.Color(color).getHexString();
  ctx.shadowColor = 'rgba(0,255,255,0.5)';
  ctx.shadowBlur = 8;
  ctx.textAlign = 'center';
  ctx.fillText(text, 128, 40);
  const texture = new THREE.CanvasTexture(canvas);
  const spriteMat = new THREE.SpriteMaterial({{ map: texture, transparent: true }});
  const sprite = new THREE.Sprite(spriteMat);
  sprite.position.copy(position);
  sprite.scale.set(6, 1.5, 1);
  scene.add(sprite);
}}

makeLabel('Time (t)', new THREE.Vector3(0, -2.0, scaleZ / 2 + 3));
makeLabel('Maturity (τ)', new THREE.Vector3(scaleX / 2 + 4, -2.0, 0));
makeLabel('Yield %', new THREE.Vector3(-scaleX / 2 - 3, scaleY / 2, -scaleZ / 2 - 1));

// Y-axis tick labels
for (let i = 0; i <= 4; i++) {{
  const yVal = yMin + (yRange * i / 4);
  const yPos = (i / 4) * scaleY;
  makeLabel(yVal.toFixed(2) + '%', new THREE.Vector3(-scaleX / 2 - 2, yPos, -scaleZ / 2), 0x666688);
}}

// ── RAYCASTER FOR TOOLTIP ──
const raycaster = new THREE.Raycaster();
const mouse = new THREE.Vector2();
const tooltip = document.getElementById('tooltip');

renderer.domElement.addEventListener('mousemove', (e) => {{
  mouse.x = (e.clientX / window.innerWidth) * 2 - 1;
  mouse.y = -(e.clientY / window.innerHeight) * 2 + 1;

  raycaster.setFromCamera(mouse, camera);
  const hits = raycaster.intersectObject(surfaceMesh);
  if (hits.length > 0) {{
    const face = hits[0].face;
    const idx = face.a;
    const t = surfaceT[idx] || 0;
    const tau = surfaceTau[idx] || 0;
    const y = surfaceY[idx] || 0;
    tooltip.style.display = 'block';
    tooltip.style.left = (e.clientX + 15) + 'px';
    tooltip.style.top = (e.clientY - 10) + 'px';
    tooltip.innerHTML = `t = ${{t.toFixed(2)}}Y<br>τ = ${{tau.toFixed(2)}}Y<br>Yield = ${{y.toFixed(3)}}%`;
  }} else {{
    tooltip.style.display = 'none';
  }}
}});

// ── ANIMATION LOOP ──
const clock = new THREE.Clock();

function animate() {{
  requestAnimationFrame(animate);
  const elapsed = clock.getElapsedTime();

  // Animate particles (antigravity float)
  if (particleCount > 0) {{
    const pos = particles.geometry.attributes.position.array;
    for (let i = 0; i < particleCount; i++) {{
      pos[i * 3] += pVelocities[i * 3] + Math.sin(elapsed * 0.3 + i) * 0.003;
      pos[i * 3 + 1] += pVelocities[i * 3 + 1] + Math.sin(elapsed * 0.5 + i * 0.7) * 0.005;
      pos[i * 3 + 2] += pVelocities[i * 3 + 2] + Math.cos(elapsed * 0.4 + i * 0.3) * 0.003;
      // Wrap around
      if (Math.abs(pos[i * 3]) > 30) pos[i * 3] *= -0.9;
      if (pos[i * 3 + 1] > 28 || pos[i * 3 + 1] < -2) pVelocities[i * 3 + 1] *= -1;
      if (Math.abs(pos[i * 3 + 2]) > 30) pos[i * 3 + 2] *= -0.9;
    }}
    particles.geometry.attributes.position.needsUpdate = true;
  }}

  // Subtle surface breathing
  const posAttr = surfaceMesh.geometry.attributes.position;
  const origY = [];
  for (let i = 0; i < posAttr.count; i++) {{
    const baseY = ((surfaceY[i] - yMin) / yRange) * scaleY;
    posAttr.setY(i, baseY + Math.sin(elapsed * 0.8 + surfaceT[i] * 2 + surfaceTau[i]) * 0.08);
  }}
  posAttr.needsUpdate = true;
  surfaceMesh.geometry.computeVertexNormals();

  // Pulse lights
  pointLight1.intensity = 1.5 + Math.sin(elapsed * 1.2) * 0.3;
  pointLight2.intensity = 1.2 + Math.cos(elapsed * 0.9) * 0.2;

  controls.update();
  renderer.render(scene, camera);
}}

animate();

// ── RESIZE ──
window.addEventListener('resize', () => {{
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(window.innerWidth, window.innerHeight);
}});

</script>
</body>
</html>
"""


config = {
    "color_scheme": color_scheme,
    "show_wireframe": show_wireframe,
    "show_particles": show_particles,
    "auto_rotate": auto_rotate,
}

threejs_html = build_threejs_html(data, config)

# Render the 3D surface
st.components.v1.html(threejs_html, height=700, scrolling=False)

# ── Rate Paths Chart (2D) ────────────────────────────────────────────────────
st.markdown("---")
st.subheader("Simulated Short Rate Paths")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(14, 4))
fig.patch.set_facecolor("#0a0a1a")
ax.set_facecolor("#0a0a1a")

times_arr = np.array(data["times"])
paths_arr = np.array(data["paths"])
mean_arr = np.array(data["mean_path"])

n_show = min(n_display_paths, paths_arr.shape[0])
for i in range(n_show):
    ax.plot(times_arr, paths_arr[i], alpha=0.15, linewidth=0.6, color="#00ffff")

ax.plot(times_arr, mean_arr, color="#ff00ff", linewidth=2, label="Mean")

p5 = np.percentile(paths_arr, 5, axis=0)
p95 = np.percentile(paths_arr, 95, axis=0)
ax.fill_between(times_arr, p5, p95, alpha=0.1, color="#00ffff", label="5–95th pct")

ax.set_xlabel("Time (years)", color="#888")
ax.set_ylabel("Rate (%)", color="#888")
ax.legend(facecolor="#0a0a1a", edgecolor="#333", labelcolor="#ccc")
ax.tick_params(colors="#666")
for spine in ax.spines.values():
    spine.set_color("#333")
ax.grid(True, alpha=0.15, color="#333")

st.pyplot(fig, use_container_width=True)
plt.close(fig)

# ── Model Info ────────────────────────────────────────────────────────────────
st.markdown("---")

with st.expander("Model Details", expanded=False):
    if model_name == "Vasicek":
        st.latex(r"dr_t = \kappa(\theta - r_t)\,dt + \sigma\,dW_t")
        st.markdown(f"""
        | Parameter | Value |
        |-----------|-------|
        | κ (mean reversion) | {kappa:.3f} |
        | θ (long-run mean)  | {theta*100:.2f}% |
        | σ (volatility)     | {sigma*100:.2f}% |
        | r₀ (initial rate)  | {r0*100:.2f}% |
        """)
    elif model_name == "CIR":
        st.latex(r"dr_t = \kappa(\theta - r_t)\,dt + \sigma\sqrt{r_t}\,dW_t")
        feller = 2 * kappa * theta
        st.markdown(f"Feller condition: 2κθ = {feller:.4f} {'>' if feller > sigma**2 else '≤'} σ² = {sigma**2:.6f}")
    elif model_name == "Hull-White":
        st.latex(r"dr_t = [\theta(t) - \kappa r_t]\,dt + \sigma\,dW_t")
        st.markdown("θ(t) is calibrated to fit the initial forward rate curve.")
    else:
        st.latex(r"dr_t = \theta(t)\,dt + \sigma\,dW_t")
        st.markdown("θ(t) = ∂f(0,t)/∂t + σ²t — derived from the initial forward rate curve.")
